/*
 * File: app/view/DateFieldExampleViewModel.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CalendarMatrix.view.DateFieldExampleViewModel', {
    extend: 'Ext.app.ViewModel',
    alias: 'viewmodel.datefieldexample',

    requires: [
        'Ext.data.Store',
        'Ext.data.proxy.Memory',
        'Ext.data.field.String',
        'Ext.data.field.Date',
        'Ext.data.field.Integer'
    ],

    stores: {
        myModels: {
            data: [
                {
                    textfield: 'officia',
                    fromdate: '8/22/2014',
                    todate: '9/22/2014',
                    numberfield: 309
                },
                {
                    textfield: 'nihil',
                    fromdate: '4/9/2013',
                    todate: '4/15/2013',
                    numberfield: 402
                },
                {
                    textfield: 'quisquam',
                    fromdate: '8/13/2006',
                    todate: '9/1/2006',
                    numberfield: 500
                },
                {
                    textfield: 'quisquam',
                    fromdate: '2/3/2007',
                    todate: '2/13/2007',
                    numberfield: 864
                },
                {
                    textfield: 'sunt',
                    fromdate: '9/13/2003',
                    todate: '9/23/2003',
                    numberfield: 786
                },
                {
                    textfield: 'eum',
                    fromdate: '5/3/2011',
                    todate: '6/3/2011',
                    numberfield: 355
                },
                {
                    textfield: 'nobis',
                    fromdate: '5/2/2014',
                    todate: '5/22/2014',
                    numberfield: 138
                },
                {
                    textfield: 'facilis',
                    fromdate: '9/13/2002',
                    todate: '9/14/2002',
                    numberfield: 550
                },
                {
                    textfield: 'praesentium',
                    fromdate: '5/11/2012',
                    todate: '5/21/2012',
                    numberfield: 675
                },
                {
                    textfield: 'asperiores',
                    fromdate: '3/19/2002',
                    todate: '5/19/2002',
                    numberfield: 779
                }
            ],
            proxy: {
                type: 'memory'
            },
            fields: [
                {
                    type: 'string',
                    name: 'textfield'
                },
                {
                    type: 'date',
                    name: 'fromdate'
                },
                {
                    type: 'date',
                    name: 'todate'
                },
                {
                    type: 'int',
                    name: 'numberfield'
                }
            ]
        }
    }

});