/*
 * File: app/view/MatrixEx2ViewController.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CalendarMatrix.view.MatrixEx2ViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.matrixex2',

    control: {
        "container#matrixEx2Cal": {
            calendarselect: 'onCalendarMatrixSelect',
            monthselect: 'onMonthSelect',
            mouseover: 'onDateMouseOver'
        },
        "button#resetBtn": {
            click: 'onResetBtnClick'
        }
    },

    onCalendarMatrixSelect: function(matrix, selDt, selDate, selVal) {
        var dts = Ext.Array.sort(Ext.Array.pluck(matrix.selectedDts, 'selectedDt'));
        this.lookupReference('selectedCont').update(dts.join(', '));
    },

    onMonthSelect: function(calendar, minDate, maxDate) {
        // Sample Controller Action to listen to monthselect event
    },

    onDateMouseOver: function(calendar, thisDate) {
        // Sample Controller Action to listen to mouseover event

    },

    onResetBtnClick: function(button, e, eOpts) {
        this.getView().down('#matrixEx2Cal').resetMatrix();
        this.lookupReference('selectedCont').update('');
    }

});
