/*
 * File: app/controller/MyGlobalController.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CalendarMatrix.controller.MyGlobalController', {
    extend: 'Ext.app.Controller',
    alias: 'controller.myglobalcontroller',

    control: {
        "tabpanel#mytabpanel": {
            tabchange: 'onTabpanelTabChange'
        }
    },

    onTabpanelTabChange: function(tabPanel, newCard, oldCard, eOpts) {
        if (oldCard.getItemId() === 'matrixEx4' && oldCard.myWindow){
            oldCard.myWindow.setHidden(true);

            // Sample alternate logic to destroy component and reset date inputs ..
            //     Ext.destroy(oldCard.myWindow);
            //     oldCard.myWindow = undefined;
            //     oldCard.down('#endBtn').setText('mm/dd/yyyy');
            //     oldCard.down('#startBtn').setText('mm/dd/yyyy');
        }
        if (oldCard.getItemId() === 'matrixEx5' && oldCard.myWindow){
            oldCard.myWindow.setHidden(true);
        }
        if (oldCard.getItemId() === 'matrixEx6' && oldCard.myWindow){
            oldCard.myWindow.setHidden(true);
        }
        if (oldCard.getItemId() === 'matrixEx3'){
            // Reset language to English in event changed
            var cntr = oldCard.getController();
            cntr.languageCalendarOverrides(cntr, 'en', 'English');  // see mixin
            var languageSelect = cntr.lookupReference('languageSelect');
            languageSelect.setValue('en');
            if (oldCard.myWindow){
                Ext.destroy(oldCard.myWindow);
                oldCard.myWindow = undefined;
            }

            // Reset date on select button
            var day_html = cntr.lookupReference('day');
            day_html.update('SELECT');
            day_html.removeCls('button-day');
            day_html.selDate = null;
            day_html.selDt = null;
            var other_html = cntr.lookupReference('dayname_month');
            other_html.update('');

        }
    }

});
