/*
 * File: app/store/OptionsExpireStore.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CalendarMatrix.store.OptionsExpireStore', {
    extend: 'Ext.data.Store',

    requires: [
        'Ext.data.field.Field'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'OptionsExpireStore',
            data: [
                {
                    ID: '1',
                    cls: 'holiday',
                    priorDt: '2013-09-02',
                    descr: 'Labor Day'
                },
                {
                    ID: '2',
                    cls: 'holiday',
                    priorDt: '2013-11-28',
                    descr: 'Thanksgiving'
                },
                {
                    ID: '3',
                    cls: 'holiday',
                    priorDt: '2013-12-25',
                    descr: 'Christmas'
                },
                {
                    ID: '4',
                    cls: 'holiday',
                    priorDt: '2014-01-01',
                    descr: 'New Years Day'
                },
                {
                    ID: '5',
                    cls: 'holiday',
                    priorDt: '2014-01-20',
                    descr: 'Martin Luther King Day'
                },
                {
                    ID: '6',
                    cls: 'holiday',
                    priorDt: '2014-02-17',
                    descr: 'Washington\'s Birthday'
                },
                {
                    ID: '7',
                    cls: 'holiday',
                    priorDt: '2014-04-18',
                    descr: 'Good Friday'
                },
                {
                    ID: '8',
                    cls: 'holiday',
                    priorDt: '2014-05-26',
                    descr: 'Memorial Day'
                },
                {
                    ID: '9',
                    cls: 'holiday',
                    priorDt: '2014-07-04',
                    descr: '4th of July'
                },
                {
                    ID: '10',
                    cls: 'holiday',
                    priorDt: '2014-09-01',
                    descr: 'Labor Day'
                },
                {
                    ID: '11',
                    cls: 'holiday',
                    priorDt: '2014-11-27',
                    descr: 'Thanksgiving'
                },
                {
                    ID: '12',
                    cls: 'holiday',
                    priorDt: '2014-12-25',
                    descr: 'Christmas'
                },
                {
                    ID: '100',
                    cls: 'holiday',
                    priorDt: '2015-01-01',
                    descr: 'New Years Day'
                },
                {
                    ID: '101',
                    cls: 'holiday',
                    priorDt: '2015-01-19',
                    descr: 'Martin Luther King Day'
                },
                {
                    ID: '102',
                    cls: 'holiday',
                    priorDt: '2015-02-25',
                    descr: 'Washingtons Birthday'
                },
                {
                    ID: '103',
                    cls: 'holiday',
                    priorDt: '2015-04-03',
                    descr: 'Good Friday'
                },
                {
                    ID: '104',
                    cls: 'holiday',
                    priorDt: '2015-05-25',
                    descr: 'Memorial Day'
                },
                {
                    ID: '105',
                    cls: 'holiday',
                    priorDt: '2015-07-03',
                    descr: '4th of July'
                },
                {
                    ID: '106',
                    cls: 'holiday',
                    priorDt: '2015-09-07',
                    descr: 'Labor Day'
                },
                {
                    ID: '107',
                    cls: 'holiday',
                    priorDt: '2015-11-26',
                    descr: 'Thanksgiving'
                },
                {
                    ID: '108',
                    cls: 'holiday',
                    priorDt: '2015-12-25',
                    descr: 'Christmas'
                },
                {
                    ID: '109',
                    cls: 'holiday',
                    priorDt: '2016-01-01',
                    descr: 'New Years Day'
                },
                {
                    ID: '110',
                    cls: 'holiday',
                    priorDt: '2016-01-18',
                    descr: 'Martin Luther King Day'
                },
                {
                    ID: '111',
                    cls: 'holiday',
                    priorDt: '2016-02-15',
                    descr: 'Washingtons Birthday'
                },
                {
                    ID: '112',
                    cls: 'holiday',
                    priorDt: '2016-03-25',
                    descr: 'Good Friday'
                },
                {
                    ID: '113',
                    cls: 'holiday',
                    priorDt: '2016-05-30',
                    descr: 'Memorial Day'
                },
                {
                    ID: '114',
                    cls: 'holiday',
                    priorDt: '2016-07-04',
                    descr: '4th of July'
                },
                {
                    ID: '115',
                    cls: 'holiday',
                    priorDt: '2016-09-05',
                    descr: 'Labor Day'
                },
                {
                    ID: '116',
                    cls: 'holiday',
                    priorDt: '2016-11-24',
                    descr: 'Thanksgiving'
                },
                {
                    ID: '117',
                    cls: 'holiday',
                    priorDt: '2016-12-26',
                    descr: 'Christmas'
                },
                {
                    ID: '13',
                    cls: 'stopTrading',
                    priorDt: '2013-09-20',
                    descr: null
                },
                {
                    ID: '14',
                    cls: 'stopTrading',
                    priorDt: '2013-10-18',
                    descr: null
                },
                {
                    ID: '15',
                    cls: 'stopTrading',
                    priorDt: '2013-11-15',
                    descr: null
                },
                {
                    ID: '16',
                    cls: 'stopTrading',
                    priorDt: '2013-12-20',
                    descr: null
                },
                {
                    ID: '17',
                    cls: 'stopTrading',
                    priorDt: '2014-01-17',
                    descr: null
                },
                {
                    ID: '18',
                    cls: 'stopTrading',
                    priorDt: '2014-02-21',
                    descr: null
                },
                {
                    ID: '19',
                    cls: 'stopTrading',
                    priorDt: '2014-03-21',
                    descr: null
                },
                {
                    ID: '20',
                    cls: 'stopTrading',
                    priorDt: '2014-05-16',
                    descr: null
                },
                {
                    ID: '21',
                    cls: 'stopTrading',
                    priorDt: '2014-06-20',
                    descr: null
                },
                {
                    ID: '22',
                    cls: 'stopTrading',
                    priorDt: '2014-07-18',
                    descr: null
                },
                {
                    ID: '23',
                    cls: 'stopTrading',
                    priorDt: '2014-08-15',
                    descr: null
                },
                {
                    ID: '24',
                    cls: 'stopTrading',
                    priorDt: '2014-09-19',
                    descr: null
                },
                {
                    ID: '25',
                    cls: 'stopTrading',
                    priorDt: '2014-10-17',
                    descr: null
                },
                {
                    ID: '26',
                    cls: 'stopTrading',
                    priorDt: '2014-11-21',
                    descr: null
                },
                {
                    ID: '27',
                    cls: 'stopTrading',
                    priorDt: '2014-12-19',
                    descr: null
                },
                {
                    ID: '118',
                    cls: 'stopTrading',
                    priorDt: '2015-01-16',
                    descr: null
                },
                {
                    ID: '119',
                    cls: 'stopTrading',
                    priorDt: '2015-02-20',
                    descr: null
                },
                {
                    ID: '120',
                    cls: 'stopTrading',
                    priorDt: '2015-03-20',
                    descr: null
                },
                {
                    ID: '121',
                    cls: 'stopTrading',
                    priorDt: '2015-04-17',
                    descr: null
                },
                {
                    ID: '122',
                    cls: 'stopTrading',
                    priorDt: '2015-05-15',
                    descr: null
                },
                {
                    ID: '123',
                    cls: 'stopTrading',
                    priorDt: '2015-06-19',
                    descr: null
                },
                {
                    ID: '124',
                    cls: 'stopTrading',
                    priorDt: '2015-07-17',
                    descr: null
                },
                {
                    ID: '125',
                    cls: 'stopTrading',
                    priorDt: '2015-08-21',
                    descr: null
                },
                {
                    ID: '126',
                    cls: 'stopTrading',
                    priorDt: '2015-09-18',
                    descr: null
                },
                {
                    ID: '127',
                    cls: 'stopTrading',
                    priorDt: '2015-10-16',
                    descr: null
                },
                {
                    ID: '128',
                    cls: 'stopTrading',
                    priorDt: '2015-11-20',
                    descr: null
                },
                {
                    ID: '129',
                    cls: 'stopTrading',
                    priorDt: '2015-12-18',
                    descr: null
                },
                {
                    ID: '130',
                    cls: 'stopTrading',
                    priorDt: '2016-01-15',
                    descr: null
                },
                {
                    ID: '131',
                    cls: 'stopTrading',
                    priorDt: '2016-02-19',
                    descr: null
                },
                {
                    ID: '132',
                    cls: 'stopTrading',
                    priorDt: '2016-03-18',
                    descr: null
                },
                {
                    ID: '133',
                    cls: 'stopTrading',
                    priorDt: '2016-04-15',
                    descr: null
                },
                {
                    ID: '134',
                    cls: 'stopTrading',
                    priorDt: '2016-05-20',
                    descr: null
                },
                {
                    ID: '135',
                    cls: 'stopTrading',
                    priorDt: '2016-06-17',
                    descr: null
                },
                {
                    ID: '136',
                    cls: 'stopTrading',
                    priorDt: '2016-07-15',
                    descr: null
                },
                {
                    ID: '137',
                    cls: 'stopTrading',
                    priorDt: '2016-08-19',
                    descr: null
                },
                {
                    ID: '138',
                    cls: 'stopTrading',
                    priorDt: '2016-09-16',
                    descr: null
                },
                {
                    ID: '139',
                    cls: 'stopTrading',
                    priorDt: '2016-10-21',
                    descr: null
                },
                {
                    ID: '140',
                    cls: 'stopTrading',
                    priorDt: '2016-11-18',
                    descr: null
                },
                {
                    ID: '141',
                    cls: 'stopTrading',
                    priorDt: '2016-12-16',
                    descr: null
                },
                {
                    ID: '28',
                    cls: 'optionsExpire',
                    priorDt: '2013-09-21',
                    descr: null
                },
                {
                    ID: '29',
                    cls: 'optionsExpire',
                    priorDt: '2013-10-19',
                    descr: null
                },
                {
                    ID: '30',
                    cls: 'optionsExpire',
                    priorDt: '2013-11-16',
                    descr: null
                },
                {
                    ID: '31',
                    cls: 'optionsExpire',
                    priorDt: '2013-12-21',
                    descr: null
                },
                {
                    ID: '32',
                    cls: 'optionsExpire',
                    priorDt: '2014-01-18',
                    descr: null
                },
                {
                    ID: '33',
                    cls: 'optionsExpire',
                    priorDt: '2014-02-22',
                    descr: null
                },
                {
                    ID: '34',
                    cls: 'optionsExpire',
                    priorDt: '2014-03-22',
                    descr: null
                },
                {
                    ID: '35',
                    cls: 'optionsExpire',
                    priorDt: '2014-04-19',
                    descr: null
                },
                {
                    ID: '36',
                    cls: 'optionsExpire',
                    priorDt: '2014-05-17',
                    descr: null
                },
                {
                    ID: '37',
                    cls: 'optionsExpire',
                    priorDt: '2014-06-21',
                    descr: null
                },
                {
                    ID: '38',
                    cls: 'optionsExpire',
                    priorDt: '2014-07-19',
                    descr: null
                },
                {
                    ID: '39',
                    cls: 'optionsExpire',
                    priorDt: '2014-08-16',
                    descr: null
                },
                {
                    ID: '40',
                    cls: 'optionsExpire',
                    priorDt: '2014-09-20',
                    descr: null
                },
                {
                    ID: '41',
                    cls: 'optionsExpire',
                    priorDt: '2014-10-18',
                    descr: null
                },
                {
                    ID: '42',
                    cls: 'optionsExpire',
                    priorDt: '2014-11-22',
                    descr: null
                },
                {
                    ID: '43',
                    cls: 'optionsExpire',
                    priorDt: '2014-12-20',
                    descr: null
                },
                {
                    ID: '142',
                    cls: 'optionsExpire',
                    priorDt: '2015-01-17',
                    descr: null
                },
                {
                    ID: '143',
                    cls: 'optionsExpire',
                    priorDt: '2015-02-21',
                    descr: null
                },
                {
                    ID: '144',
                    cls: 'optionsExpire',
                    priorDt: '2015-03-31',
                    descr: null
                },
                {
                    ID: '145',
                    cls: 'optionsExpire',
                    priorDt: '2015-04-18',
                    descr: null
                },
                {
                    ID: '146',
                    cls: 'optionsExpire',
                    priorDt: '2015-05-16',
                    descr: null
                },
                {
                    ID: '147',
                    cls: 'optionsExpire',
                    priorDt: '2015-06-20',
                    descr: null
                },
                {
                    ID: '148',
                    cls: 'optionsExpire',
                    priorDt: '2015-07-18',
                    descr: null
                },
                {
                    ID: '149',
                    cls: 'optionsExpire',
                    priorDt: '2015-08-22',
                    descr: null
                },
                {
                    ID: '150',
                    cls: 'optionsExpire',
                    priorDt: '2015-09-19',
                    descr: null
                },
                {
                    ID: '151',
                    cls: 'optionsExpire',
                    priorDt: '2001-10-17',
                    descr: null
                },
                {
                    ID: '152',
                    cls: 'optionsExpire',
                    priorDt: '2015-11-21',
                    descr: null
                },
                {
                    ID: '153',
                    cls: 'optionsExpire',
                    priorDt: '2015-12-19',
                    descr: null
                },
                {
                    ID: '154',
                    cls: 'optionsExpire',
                    priorDt: '2016-01-16',
                    descr: null
                },
                {
                    ID: '155',
                    cls: 'optionsExpire',
                    priorDt: '2016-02-20',
                    descr: null
                },
                {
                    ID: '156',
                    cls: 'optionsExpire',
                    priorDt: '2016-03-19',
                    descr: null
                },
                {
                    ID: '157',
                    cls: 'optionsExpire',
                    priorDt: '2016-04-16',
                    descr: null
                },
                {
                    ID: '158',
                    cls: 'optionsExpire',
                    priorDt: '2016-05-21',
                    descr: null
                },
                {
                    ID: '159',
                    cls: 'optionsExpire',
                    priorDt: '2016-06-18',
                    descr: null
                },
                {
                    ID: '160',
                    cls: 'optionsExpire',
                    priorDt: '2016-07-16',
                    descr: null
                },
                {
                    ID: '161',
                    cls: 'optionsExpire',
                    priorDt: '2016-08-20',
                    descr: null
                },
                {
                    ID: '162',
                    cls: 'optionsExpire',
                    priorDt: '2016-09-17',
                    descr: null
                },
                {
                    ID: '163',
                    cls: 'optionsExpire',
                    priorDt: '2016-10-22',
                    descr: null
                },
                {
                    ID: '164',
                    cls: 'optionsExpire',
                    priorDt: '2016-11-19',
                    descr: null
                },
                {
                    ID: '165',
                    cls: 'optionsExpire',
                    priorDt: '2016-12-17',
                    descr: null
                },
                {
                    ID: '44',
                    cls: 'quarterlyExpiration',
                    priorDt: '2013-09-30',
                    descr: null
                },
                {
                    ID: '45',
                    cls: 'quarterlyExpiration',
                    priorDt: '2013-12-31',
                    descr: null
                },
                {
                    ID: '46',
                    cls: 'quarterlyExpiration',
                    priorDt: '2014-03-31',
                    descr: null
                },
                {
                    ID: '47',
                    cls: 'quarterlyExpiration',
                    priorDt: '2014-06-30',
                    descr: null
                },
                {
                    ID: '48',
                    cls: 'quarterlyExpiration',
                    priorDt: '2014-09-30',
                    descr: null
                },
                {
                    ID: '49',
                    cls: 'quarterlyExpiration',
                    priorDt: '2014-12-31',
                    descr: null
                },
                {
                    ID: '166',
                    cls: 'quarterlyExpiration',
                    priorDt: '2015-03-31',
                    descr: null
                },
                {
                    ID: '167',
                    cls: 'quarterlyExpiration',
                    priorDt: '2015-06-30',
                    descr: null
                },
                {
                    ID: '168',
                    cls: 'quarterlyExpiration',
                    priorDt: '2015-09-30',
                    descr: null
                },
                {
                    ID: '169',
                    cls: 'quarterlyExpiration',
                    priorDt: '2015-12-31',
                    descr: null
                },
                {
                    ID: '170',
                    cls: 'quarterlyExpiration',
                    priorDt: '2016-03-31',
                    descr: null
                },
                {
                    ID: '171',
                    cls: 'quarterlyExpiration',
                    priorDt: '2016-06-30',
                    descr: null
                },
                {
                    ID: '172',
                    cls: 'quarterlyExpiration',
                    priorDt: '2016-09-30',
                    descr: null
                },
                {
                    ID: '173',
                    cls: 'quarterlyExpiration',
                    priorDt: '2016-12-30',
                    descr: null
                }
            ],
            fields: [
                {
                    name: 'id'
                },
                {
                    name: 'cls'
                },
                {
                    name: 'priorDt'
                },
                {
                    name: 'descr'
                }
            ]
        }, cfg)]);
    }
});